### ISSUE TITLE
Some wav files won't play in FireFox

### ISSUE THREAD

**Issue by iver56** [gdsp/gdsp#11]
Every time vocodaconv.wav appears as the original sound in a listening test, the player for the original sound disappears, but I can play the processed sound. This occurs in Firefox, but not in Chrome.

![missing-sound](https://cloud.githubusercontent.com/assets/1470603/9633238/14e00dca-518c-11e5-94c2-95edef0a9df2.png)

I suspect that the culprit is incompatible file format. Perhaps converting/normalizing vocodaconv.wav somehow helps?

**Comment by iver56** [comment]
Related:
http://stackoverflow.com/a/10406276/2319697

**Comment by Oeyvind** [comment]
ah, den var 24 bit ja,
takk for presist spotta, jeg har bytta ut fila på serveren nå.

2015-09-02 16:04 GMT+02:00 iver56 <notifications@github.com>:

> Related:
> http://stackoverflow.com/a/10406276/2319697
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdsp/gdsp/issues/11#issuecomment-137092736>.
>



-- 

Oeyvind Brandtsegg
Professor of Music Technology
NTNU
7491 Trondheim
Norway
Cell: +47 92 203 205

http://flyndresang.no/
http://www.partikkelaudio.com/
http://soundcloud.com/brandtsegg
http://soundcloud.com/t-emp

**Comment by iver56** [comment]
Thanks, that did the trick
